[versions]
openrndr = "0.4.5"
orx = "0.4.5"

[libraries]
openrndr-color = { group = "org.openrndr", name = "openrndr-color", version.ref = "openrndr" }
openrndr-math = { group = "org.openrndr", name = "openrndr-math", version.ref = "openrndr" }
orx-color = { group = "org.openrndr.extra", name = "orx-color", version.ref = "orx" }
